#!/bin/bash
echo "*******************************"
echo   "Running git pre-commit hook"
echo "*******************************"

echo "*******************************"
echo   "Running detekt"
echo "*******************************"

./gradlew detekt
RESULT=$?

exit $RESULT