build:
  maxIssues: 0
  weights:
  # complexity: 2
  # LongParameterList: 1
  # style: 1
  # comments: 1

processors:
  active: false
  exclude:
  # - 'FunctionCountProcessor'
  # - 'PropertyCountProcessor'
  # - 'ClassCountProcessor'
  # - 'PackageCountProcessor'
  # - 'KtFileCountProcessor'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
  #  - 'FindingsReport'
  #  - 'BuildFailureReport'

comments:
  # No rules requiring type resolution
  active: true
  excludes: &testFolders
    - '**/test/**'
    - '**/androidTest/**'
    - '**/*.Test.kt'
    - '**/*.Spec.kt'
    - '**/*.Spek.kt'
  AbsentOrWrongFileLicense:
    active: true
  CommentOverPrivateFunction:
    active: false
    excludes: &noDocNecessary
      - '**/sample/**'
      - '**/samples/**'
      - '**/storybook/**'
      - '**/studio/**'
      - '**/build/generated/ksp/**'
  CommentOverPrivateProperty:
    active: false
    excludes: *noDocNecessary
  DeprecatedBlockTag:
    active: true
  EndOfSentenceFormat:
    active: false
    excludes: *noDocNecessary
    endOfSentenceFormat: ([.?!][ \t\n\r\f<])|([.?!:]$)
  KDocReferencesNonPublicProperty:
    active: true
  OutdatedDocumentation:
    active: true
    excludes: *noDocNecessary
    allowParamOnConstructorProperties: true
  UndocumentedPublicClass:
    active: true
    ignoreDefaultCompanionObject: true
    excludes: *noDocNecessary
  UndocumentedPublicFunction:
    active: true
    excludes: *noDocNecessary
    ignoreAnnotated: [ 'VisibleForTesting' ]
  UndocumentedPublicProperty:
    active: false
    excludes: *noDocNecessary

complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 4
  ComplexInterface:
    active: false
    threshold: 10
    includeStaticDeclarations: false
  CyclomaticComplexMethod:
    active: true
    threshold: 15
    ignoreSingleWhenExpression: true
    ignoreSimpleWhenEntries: true
  LabeledExpression:
    active: false
    ignoredLabels: [ '' ]
  LargeClass:
    active: true
    threshold: 600
  LongMethod:
    active: true
    excludes: *testFolders
    threshold: 60
  LongParameterList:
    active: true
    excludes: &buildFolders
      - '**/build/generated/ksp/**'
    functionThreshold: 16
    constructorThreshold: 16
    ignoreDefaultParameters: true
  MethodOverloading:
    active: false
    threshold: 6
  NestedBlockDepth:
    active: true
    threshold: 4
  StringLiteralDuplication:
    active: false
    excludes: *testFolders
    threshold: 3
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: true
    ignoreStringsRegex: '$^'
  TooManyFunctions:
    active: true
    excludes: *testFolders
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20
    ignoreAnnotatedFunctions: ['Preview']
    ignoreDeprecated: false
    ignoreOverridden: true
    ignorePrivate: true

empty-blocks:
  active: true
  # No rules requiring type resolution
  EmptyCatchBlock:
    active: true
    allowedExceptionNameRegex: '^(_|(ignore|expected).*)'
  EmptyClassBlock:
    active: true
  EmptyDefaultConstructor:
    active: true
    excludes: *buildFolders
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: true
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

exceptions:
  active: true
  ExceptionRaisedInUnexpectedLocation:
    active: false
    methodNames:
      - 'toString'
      - 'hashCode'
      - 'equals'
      - 'finalize'
  InstanceOfCheckForException:
    active: false
    excludes: *testFolders
  NotImplementedDeclaration:
    active: false
  PrintStackTrace:
    active: false
  RethrowCaughtException:
    active: false
  ReturnFromFinally:
    active: false
  SwallowedException:
    active: false
    ignoredExceptionTypes: [ 'InterruptedException,NumberFormatException,ParseException,MalformedURLException' ]
  ThrowingExceptionFromFinally:
    active: false
  ThrowingExceptionInMain:
    active: false
  ThrowingExceptionsWithoutMessageOrCause:
    active: false
    exceptions: [ 'IllegalArgumentException,IllegalStateException,IOException' ]
  ThrowingNewInstanceOfSameException:
    active: false
  TooGenericExceptionCaught:
    active: false
    excludes: *testFolders
    exceptionNames:
      - ArrayIndexOutOfBoundsException
      - Error
      - Exception
      - IllegalMonitorStateException
      - NullPointerException
      - IndexOutOfBoundsException
      - RuntimeException
      - Throwable
    allowedExceptionNameRegex: [ '^(_|(ignore|expected).*)' ]
  TooGenericExceptionThrown:
    active: false
    exceptionNames:
      - Error
      - Exception
      - Throwable
      - RuntimeException

formatting:
  active: true
  android: true
  autoCorrect: true
  excludes: *buildFolders
  # No rules requiring type resolution
  AnnotationOnSeparateLine:
    active: false
  ChainWrapping:
    active: true
    autoCorrect: true
  CommentSpacing:
    active: true
    autoCorrect: true
  Filename:
    active: true
  FinalNewline:
    active: true
    autoCorrect: true
  ImportOrdering:
    active: false
    autoCorrect: true
  Indentation:
    active: false
    indentSize: 4
  MaximumLineLength:
    active: true
    excludes: *testFolders
    maxLineLength: 240
  ModifierOrdering:
    active: true
    autoCorrect: true
  MultiLineIfElse:
    active: true
    autoCorrect: true
  NoBlankLineBeforeRbrace:
    active: true
    autoCorrect: true
  NoConsecutiveBlankLines:
    active: true
    autoCorrect: true
  NoEmptyClassBody:
    active: true
    autoCorrect: true
  NoLineBreakAfterElse:
    active: true
    autoCorrect: true
  NoLineBreakBeforeAssignment:
    active: true
    autoCorrect: true
  NoMultipleSpaces:
    active: true
    autoCorrect: true
  NoSemicolons:
    active: true
    autoCorrect: true
  NoTrailingSpaces:
    active: true
    autoCorrect: true
  NoUnitReturn:
    active: true
    autoCorrect: true
  NoUnusedImports:
    active: true
    autoCorrect: true
  NoWildcardImports:
    active: true
  PackageName:
    active: false
    autoCorrect: true
  ParameterListWrapping:
    active: false # Intentionally disabled.
    autoCorrect: true
  ParameterWrapping:
    active: true
    autoCorrect: true
    indentSize: 4
    maxLineLength: 120
  PropertyName:
    # Disabled, it collides with Composable properties
    active: false
    autoCorrect: true
    excludes: *testFolders
  PropertyWrapping:
    active: true
    autoCorrect: true
    excludes: *testFolders
    indentSize: 4
    maxLineLength: 120
  SpacingAroundAngleBrackets:
    active: true
    autoCorrect: true
  SpacingAroundColon:
    active: true
    autoCorrect: true
  SpacingAroundComma:
    active: true
    autoCorrect: true
  SpacingAroundCurly:
    active: true
    autoCorrect: true
  SpacingAroundDot:
    active: true
    autoCorrect: true
  SpacingAroundKeyword:
    active: true
    autoCorrect: true
  SpacingAroundOperators:
    active: true
    autoCorrect: true
  SpacingAroundParens:
    active: true
    autoCorrect: true
  SpacingAroundRangeOperator:
    active: true
    autoCorrect: true
  StringTemplate:
    active: true
    autoCorrect: true

naming:
  active: true
  ClassNaming:
    active: true
    excludes: *testFolders
    classPattern: '[A-Z$][a-zA-Z0-9$]*'
  ConstructorParameterNaming:
    active: true
    excludes: *testFolders
    parameterPattern: '[a-z][A-Za-z0-9]*'
    privateParameterPattern: '[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'
  EnumNaming:
    active: true
    excludes: *testFolders
    enumEntryPattern: '^[A-Z][_a-zA-Z0-9]*'
  ForbiddenClassName:
    active: false
    excludes: *testFolders
    forbiddenName: [ '' ]
  FunctionMaxLength:
    active: false
    excludes: *testFolders
    maximumFunctionNameLength: 30
  FunctionMinLength:
    active: false
    excludes: *testFolders
    minimumFunctionNameLength: 3
  FunctionNaming:
    active: true
    excludes: *testFolders
    functionPattern: '^([a-z$][a-zA-Z$0-9]*)|(`.*`)$'
    excludeClassPattern: '$^'
    ignoreAnnotated: [ 'Composable' ]
  FunctionParameterNaming:
    active: true
    excludes: &testAndBuildFolders
      - '**/test/**'
      - '**/androidTest/**'
      - '**/*.Test.kt'
      - '**/*.Spec.kt'
      - '**/*.Spek.kt'
      - '**/build/generated/ksp/**'
    parameterPattern: '[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'
  InvalidPackageDeclaration:
    active: false
    rootPackage: ''
  MatchingDeclarationName:
    active: true
    excludes: *buildFolders
  MemberNameEqualsClassName:
    active: false
    ignoreOverridden: true
  ObjectPropertyNaming:
    active: true
    excludes: *testFolders
    constantPattern: '[A-Za-z][_A-Za-z0-9]*'
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
    privatePropertyPattern: '(_)?[A-Za-z][_A-Za-z0-9]*'
  PackageNaming:
    active: true
    excludes: *testFolders
    packagePattern: '^[a-z]+(\.[a-z][_A-Za-z0-9]*)*$'
  TopLevelPropertyNaming:
    active: true
    excludes: *testFolders
    constantPattern: '[A-Z][_A-Za-z0-9]*'
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
    privatePropertyPattern: '_?[A-Za-z][_A-Za-z0-9]*'
  VariableMaxLength:
    active: false
    excludes: *testFolders
    maximumVariableNameLength: 64
  VariableMinLength:
    active: false
    excludes: *testFolders
    minimumVariableNameLength: 1
  VariableNaming:
    active: true
    excludes: *testAndBuildFolders
    variablePattern: '[a-z][A-Za-z0-9]*'
    privateVariablePattern: '(_)?[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'

performance:
  active: true
  # Rules not requiring type resolution.
  ForEachOnRange:
    active: true
    excludes: *testFolders
  SpreadOperator:
    active: true
    excludes: *testFolders
  UnnecessaryPartOfBinaryExpression:
    active: true
  UnnecessaryTemporaryInstantiation:
    active: true
  # Rules requiring type resolution.
  ArrayPrimitive:
    active: true
  CouldBeSequence:
    active: true

potential-bugs:
  active: true
  # Rules not requiring type resolution.
  CastToNullableType:
    active: true
  ExitOutsideMain:
    # Disabled, does not apply to Android.
    active: false
  ExplicitGarbageCollectionCall:
    active: true
  ImplicitDefaultLocale:
    active: true
  InvalidRange:
    active: true
  IteratorHasNextCallsNextMethod:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  LateinitUsage:
    # Disabled for now, high impact and no policy in place.
    active: false
    excludes: *testFolders
    ignoreAnnotated: [ '' ]
    ignoreOnClassesPattern: ''
  MapGetWithNotNullAssertionOperator:
    active: true
  MissingPackageDeclaration:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true
  UselessPostfixExpression:
    active: true
  WrongEqualsTypeParameter:
    active: true
  # Rules requiring type resolution.
  AvoidReferentialEquality:
    active: true
    forbiddenTypePatterns: ['kotlin.String']
  CastNullableToNonNullableType:
    active: true
  Deprecation:
    active: true
  DontDowncastCollectionTypes:
    active: true
  DoubleMutabilityForCollection:
    active: true
    mutableTypes:
      - 'kotlin.collections.MutableList'
      - 'kotlin.collections.MutableMap'
      - 'kotlin.collections.MutableSet'
      - 'kotlin.collections.MutableSet'
      - 'java.util.ArrayList'
      - 'java.util.LinkedHashSet'
      - 'java.util.HashSet'
      - 'java.util.LinkedHashMap'
      - 'java.util.HashMap'
  ElseCaseInsteadOfExhaustiveWhen:
    active: true
    ignoredSubjectTypes: [ '' ]
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  EqualsWithHashCodeExist:
    active: true
  HasPlatformType:
    active: true
  IgnoredReturnValue:
    active: true
    restrictToConfig: true
    returnValueAnnotations: ['CheckResult', '*.CheckResult', 'CheckReturnValue', '*.CheckReturnValue']
    ignoreReturnValueAnnotations: ['CanIgnoreReturnValue', '*.CanIgnoreReturnValue']
    returnValueTypes: ['kotlin.sequences.Sequence', 'kotlinx.coroutines.flow.*Flow', 'java.util.stream.*Stream']
    ignoreFunctionCall: []
  ImplicitUnitReturnType:
    active: true
    allowExplicitReturnType: true
  NullCheckOnMutableProperty:
    active: true
  NullableToStringCall:
    active: true
  PropertyUsedBeforeDeclaration:
    active: true
  UnnecessaryNotNullCheck:
    active: true
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true
  UnreachableCatchBlock:
    active: true
  UnreachableCode:
    active: true
  UnsafeCallOnNullableType:
    active: true
  UnsafeCast:
    active: true
  UnusedUnaryOperator:
    active: true

style:
  active: true
  BracesOnIfStatements:
    active: true
    singleLine: 'consistent'
    multiLine: 'consistent'
  BracesOnWhenStatements:
    active: false
  CollapsibleIfStatements:
    active: false
  DataClassContainsFunctions:
    active: false
    conversionFunctionPrefix: [ 'to' ]
  DataClassShouldBeImmutable:
    active: false
  EqualsNullCall:
    active: false
  EqualsOnSignatureLine:
    active: false
  ExplicitItLambdaParameter:
    active: false
  ExpressionBodySyntax:
    active: false
    includeLineWrapping: false
  ForbiddenComment:
    active: false
    comments: [ 'TODO:,FIXME:,STOPSHIP:' ]
  ForbiddenImport:
    active: true
    imports:
      - 'kotlinx.android.synthetic.*'
      - 'com.google.errorprone.annotations.Immutable'
  ForbiddenVoid:
    active: false
    ignoreOverridden: false
    ignoreUsageInGenerics: false
  FunctionOnlyReturningConstant:
    active: false
    ignoreOverridableFunction: true
    excludedFunctions: [ 'describeContents' ]
  LoopWithTooManyJumpStatements:
    active: false
    maxJumpCount: 1
  MagicNumber:
    active: true
    excludes: *testFolders
    ignoreNumbers: [ '-1', '0', '1', '2' ]
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnums: false
    ignoreRanges: false
  MayBeConst:
    active: true
  ModifierOrder:
    active: true
  NestedClassesVisibility:
    active: false
  NewLineAtEndOfFile:
    active: false
  NoTabs:
    active: false
  OptionalAbstractKeyword:
    active: true
  OptionalUnit:
    active: false
  PreferToOverPairSyntax:
    active: false
  ProtectedMemberInFinalClass:
    active: false
  RedundantVisibilityModifierRule:
    active: false
  ReturnCount:
    active: true
    max: 2
    excludedFunctions: [ 'equals' ]
    excludeLabeled: false
    excludeReturnFromLambda: true
  SafeCast:
    active: true
  SerialVersionUIDInSerializableClass:
    active: false
  SpacingBetweenPackageAndImports:
    active: false
  ThrowsCount:
    active: true
    max: 2
  TrailingWhitespace:
    active: false
  UnderscoresInNumericLiterals:
    active: false
    acceptableLength: 5
  UnnecessaryAbstractClass:
    active: false
    ignoreAnnotated: [ 'dagger.Module' ]
  UnnecessaryApply:
    active: false
  UnnecessaryInheritance:
    active: false
  UnnecessaryLet:
    active: false
  UnnecessaryParentheses:
    active: false
  UntilInsteadOfRangeTo:
    active: false
  UnusedImports:
    active: true
  UnusedPrivateClass:
    active: true
  UnusedPrivateMember:
    active: false
    allowedNames: [ '(_|ignored|expected|serialVersionUID)' ]
  UseCheckOrError:
    active: false
  UseDataClass:
    active: false
    ignoreAnnotated: [ '' ]
  UseRequire:
    active: false
  UselessCallOnNotNull:
    active: false
  UtilityClassWithPublicConstructor:
    active: false
  VarCouldBeVal:
    active: false
  WildcardImport:
    active: true
    excludes: *testFolders
    excludeImports: [ 'java.util.*' ]

# Compose: https://mrmans0n.github.io/compose-rules/rules/
# wiki: https://mrmans0n.github.io/compose-rules/rules/
# composeRules-detekt = { module = "io.nlopez.compose.rules:detekt", version.ref = "composeRules" }
# Rules in progressive activation.
Compose:
  ComposableAnnotationNaming:
    active: true
  ComposableNaming:
    active: true
  ComposableParamOrder:
    active: true
  CompositionLocalAllowlist:
    active: false
    # Locals are widely used in Kubit, this rule will remain disabled.
  CompositionLocalNaming:
    active: true
  ContentEmitterReturningValues:
    active: true
  ContentTrailingLambda:
    active: false
  DefaultsVisibility:
    active: true
    # Intentionally disabled, our DS is not meant to be consumed in public.
  LambdaParameterInRestartableEffect:
    active: false
  Material2:
    active: true
    # TODO: Activate after migration to Compose 1.7.
  ModifierClickableOrder:
    active: true
  ModifierComposed:
    active: true
  ModifierMissing:
    active: false
    # Intentionally disabled, we will allow our components not to accept external Modifiers.
  ModifierNaming:
    active: true
  ModifierNotUsedAtRoot:
    active: true
  ModifierReused:
    active: true
  ModifierWithoutDefault:
    active: true
  MultipleEmitters:
    active: true
  MutableParams:
    active: true
  MutableStateAutoboxing:
    active: true
  MutableStateParam:
    active: true
  ParameterNaming:
    active: true
  PreviewAnnotationNaming:
    active: true
  PreviewPublic:
    active: false
  RememberMissing:
    active: true
  RememberContentMissing:
    active: true
  UnstableCollections:
    active: true
  ViewModelForwarding:
    active: true
  ViewModelInjection:
    active: true
