name: Publish to Maven Central

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true

jobs:
  publish:
    runs-on: macos-latest
    environment: production
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish to Maven Central
        uses: openMF/mifos-x-actionhub-publish-library-kmp@v1.0.0
        with:
          version: ${{ github.event.inputs.version }}
          maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          gpg-key-id: ${{ secrets.GPG_SIGNING_KEY_ID }}
          gpg-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
